In [2]:
import numpy as np
from util import *

In [3]:
U = np.array([[1] + [0] * 7,
     [0] * 7 + [1],
     [0,1] + [0] * 6,
     [0,0,1] + [0] * 5,
     [0,0,0,1] + [0] * 4,
     [0,0,0,0,1] + [0] * 3,
     [0,0,0,0,0,1] + [0] * 2,
     [0,0,0,0,0,0,1] + [0] * 1])

print(U)


[[1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 1 0]]


In [4]:
simulate_unitary(U)

Simulating unitary of size 3x3 :
[[1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 1 0]] 
In: 000 Out: 000
In: 001 Out: 010
In: 010 Out: 011
In: 011 Out: 100
In: 100 Out: 101
In: 101 Out: 110
In: 110 Out: 111
In: 111 Out: 001


In [5]:
bitstring_to_array("001")

array([[0.+0.j],
       [1.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j]])

In [13]:
bitstring_to_array("111")

array([[0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [1.+0.j]])